"""empty message

Revision ID: 71be4a91b02f
Revises: 1f943a332b16
Create Date: 2022-05-11 20:04:53.171193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71be4a91b02f'
down_revision = '1f943a332b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('pitch', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###
