"""empty message

Revision ID: ccec05054ab0
Revises: da9934007397
Create Date: 2022-05-10 16:14:03.853480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccec05054ab0'
down_revision = 'da9934007397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitch_user_fkey', 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'user', ['user_id'], ['id'])
    op.drop_column('pitch', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key('pitch_user_fkey', 'pitch', 'user', ['user'], ['id'])
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###
