"""empty message

Revision ID: e2b3a6bd9aac
Revises: ccec05054ab0
Create Date: 2022-05-11 17:49:40.704975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b3a6bd9aac'
down_revision = 'ccec05054ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitch_category_fkey', 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'pitch', 'comment', ['comment_id'], ['id'])
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key('pitch_category_fkey', 'pitch', 'category', ['category'], ['id'])
    op.drop_column('pitch', 'comment_id')
    op.drop_column('pitch', 'category_id')
    # ### end Alembic commands ###
