"""empty message

Revision ID: fdae420d6c05
Revises: 71be4a91b02f
Create Date: 2022-05-12 11:28:25.221275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdae420d6c05'
down_revision = '71be4a91b02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'user', ['user_name'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_name')
    # ### end Alembic commands ###
